name: Backend CD - Test

on:
  push:
    branches: [ develop ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: AkhileshNS/heroku-deploy@v3.2.6
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "great-things-test"
        heroku_email: "josiah.sayers15@gmail.com"
        appdir: "backend"
        branch: "develop"
